### ISSUE TITLE
The extension methods should be used on Widget instead of String in Documentation

### ISSUE THREAD

**Issue by AyushBherwani1998** [iampawan/VelocityXApp#2]
**Describe the bug**
The `box` and `card` documentation uses the extension method on `String` which will throw an error.

**Expected behavior**
The extension method should be used on Widget instead of String.
```dart
Text('VelocityX').box.shadow2xl.make();
```

**Comment by iampawan** [comment]
Sorry if it was confusing, Text Widget extensions can be applied to strings and num as well. So it's all good

**Comment by AyushBherwani1998** [comment]
Yes, `Text` widget extensions can be applied but the docs also uses `Card` and `Container` extensions on String.

**Comment by iampawan** [comment]
Yes, Thanks I have merged it.
