### ISSUE TITLE
The getter VelocityX.colorColor is not defined 

### ISSUE THREAD

**Issue by sameeerkashyap** [iampawan/VelocityXApp#7]
**Describe the bug**
possible breaking changes in version 0.2.0, all getters from colors have seemed to be changed 

**To Reproduce**
1. Go to  pubspec.yaml 
2. Click on velocity_x ^0.2.0 and get packages 

**Expected behavior**
Error appear in colors_page,home_page and splash_page show errors where VelocitytX.color is used 
.
**Additional context**
Refactor required.

**Comment by iampawan** [comment]
Can you pull it again & check?

**Comment by sameeerkashyap** [comment]
sorry, my bad , it did show my branch was even with master, so didn't check. Everything seems to be fine.
